-- ============================================================================
-- Portal 4housing — Compras + EERR · 110 · ESQUEMA en wcpk (SOLO ESTRUCTURA)
-- ============================================================================
-- Replica el esquema del proyecto aaqp (Compras + EERR) dentro del proyecto
-- unificado wcpk, con prefijo compras_ para todo (salvo eerr_estado, que ya
-- viene bien prefijada). NO trae datos (eso va en 115_datos, local).
--
-- Diferencias a propósito respecto de aaqp (endurecimiento — reglas del portal):
--   * NADA para anon: cada tabla arranca con RLS on y policies solo para
--     authenticated. En aaqp había grants a anon y 3 tablas con RLS apagado.
--   * Compuerta de sector: cada policy exige tiene_sector('compras') (o 'eerr'
--     en las tablas que EERR necesita leer). Sin esto, cualquier usuario
--     autenticado de otro sector vería datos de Compras.
--   * Se preserva el modelo de acceso propio de Compras (ve_confidencial,
--     es_tesorero, es_admin) vía compras_usuarios_autorizados.
--
-- Correr en el SQL Editor de Supabase del proyecto del PORTAL (wcpk).
-- Idempotente donde se puede (create table if not exists, drop policy if exists).
-- Requiere que 000_portal_acceso.sql ya exista (enum sector_portal, tiene_sector)
-- y que 'compras' y 'eerr' estén en el enum (050 agregó 'eerr').
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0 · Secuencias explícitas (las que en aaqp eran default nextval, no identity)
-- ---------------------------------------------------------------------------
create sequence if not exists public.compras_ogs_numero_seq;
create sequence if not exists public.compras_pagos_op_seq;

-- ===========================================================================
-- 1 · TABLAS
-- ===========================================================================

create table if not exists public.compras_articulos (
  id             bigint generated by default as identity primary key,
  codigo         text,
  descripcion    text,
  cuenta_cod     text,
  cuenta         text,
  desc_adicional text,
  sinonimo       text,
  costo_ars      numeric,
  costo_usd      numeric,
  costo_fecha    date,
  costo_proveedor text
);

create table if not exists public.compras_aux_opciones (
  id           bigint generated by default as identity primary key,
  tipo_cod     text,
  cod          text,
  descripcion  text,
  habil        text,
  confidencial boolean default false,
  unique (tipo_cod, cod)
);

create table if not exists public.compras_aux_tipos (
  id           bigint generated by default as identity primary key,
  cod          text unique,
  descripcion  text,
  confidencial boolean default false
);

create table if not exists public.compras_caja (
  cod           text primary key,
  nombre        text,
  moneda        text,
  saldo_inicial numeric default 0
);

create table if not exists public.compras_caja_ingresos (
  id            bigint generated by default as identity primary key,
  fecha         date not null,
  moneda        text not null,
  importe       numeric not null,
  origen_cod    text,
  destino_cod   text,
  observaciones text,
  creado_por    text,
  creado_en     timestamptz default now()
);

create table if not exists public.compras_certificadores (
  id     bigint generated by default as identity primary key,
  nombre text
);

create table if not exists public.compras_clasif_comprobantes (
  cod         text primary key,
  descripcion text,
  habil_comp  text,
  habil_tes   text,
  habil_vta   text,
  categoria   text
);

create table if not exists public.compras_clasif_proyecto_eerr (
  codigo         text primary key,
  eerr           text not null,
  cuenta         text,
  aux            text,
  nqnable        boolean not null default false,
  migrado        boolean not null default false,
  actualizado_en timestamptz not null default now()
);

create table if not exists public.compras_clasif_renglon (
  id          bigint generated by default as identity primary key,
  codigo      text unique,
  descripcion text,
  eerr        text,
  cuenta_cod  text,
  aux         text,
  nqnable     boolean default false,
  migrado     boolean default false
);

create table if not exists public.compras_cuentas (
  id          bigint generated by default as identity primary key,
  codigo      text,
  descripcion text,
  clase       text,
  restringido boolean default false
);

create table if not exists public.compras_cuentas_contables (
  id           bigint generated by default as identity primary key,
  cod          text unique,
  descripcion  text,
  clase        text,
  tipo         text,
  saldo        text,
  usa_aux      text,
  habil        text,
  confidencial boolean default false
);

create table if not exists public.compras_depositos (
  id           bigint generated by default as identity primary key,
  codigo       text not null unique,
  descripcion  text,
  direccion    text,
  inhabilitado text default 'No',
  sucursal     text
);

-- EERR: estado clave/valor (JSON). Mantiene su nombre (ya prefijado eerr_).
create table if not exists public.eerr_estado (
  clave          text primary key,
  valor          jsonb,
  actualizado_en timestamptz default now()
);

create table if not exists public.compras_herramientas (
  id          bigint generated by default as identity primary key,
  codigo      text,
  descripcion text,
  categoria   text,
  serie       text,
  marca       text,
  deposito    text,
  alta        text,
  created_at  timestamptz default now()
);

create table if not exists public.compras_herr_operaciones (
  id              bigint generated by default as identity primary key,
  herr_id         bigint,
  tipo            text,
  fecha           date,
  persona         text,
  desde           date,
  hasta           date,
  precio          numeric,
  fecha_envio     date,
  fecha_recepcion date,
  proveedor       text,
  oc              text,
  costo           numeric,
  created_at      timestamptz default now()
);

create table if not exists public.compras_idx_cac (
  periodo      integer primary key,
  construccion numeric,
  materiales   numeric,
  mano_obra    numeric
);

create table if not exists public.compras_idx_dolar_blue (
  periodo integer primary key,
  compra  numeric
);

create table if not exists public.compras_idx_dolar_oficial (
  periodo integer primary key,
  compra  numeric
);

create table if not exists public.compras_idx_facpce (
  periodo integer primary key,
  valor   numeric
);

create table if not exists public.compras_idx_ipc (
  periodo  integer primary key,
  nacional numeric,
  empalme  numeric
);

create table if not exists public.compras_idx_poli (
  periodo  integer primary key,
  mo       numeric,
  art_ilum numeric,
  maq_imp  numeric,
  hierros  numeric,
  equipo   numeric,
  gastos   numeric
);

create table if not exists public.compras_idx_sueldos (
  periodo integer primary key,
  ars     numeric,
  pct     numeric
);

create table if not exists public.compras_idx_uva (
  periodo integer primary key,
  valor   numeric
);

create table if not exists public.compras_mantenimiento (
  id           bigint generated by default as identity primary key,
  anio         integer,
  bien         text,
  marca        text,
  detalle      text,
  periodicidad text,
  empresa      text,
  responsable  text,
  presupuesto  numeric default 0,
  oc           text,
  costo_real   numeric default 0,
  observaciones text,
  meses        jsonb default '{}'::jsonb,
  unidades     jsonb default '[]'::jsonb,
  checklist    jsonb default '[]'::jsonb,
  created_at   timestamptz default now()
);

create table if not exists public.compras_inspecciones (
  id            bigint generated by default as identity primary key,
  item_id       bigint,
  periodo       text,
  fecha         date,
  sitio         text,
  resultados    jsonb default '{}'::jsonb,
  observaciones text,
  accion        text,
  created_at    timestamptz default now()
);

create table if not exists public.compras_modulos (
  id       bigint generated by default as identity primary key,
  etiqueta text
);

create table if not exists public.compras_motivos_cierre (
  id          bigint generated by default as identity primary key,
  descripcion text not null unique,
  activo      boolean default true
);

create table if not exists public.compras_oc_informe (
  id                 bigint generated by default as identity primary key,
  fecha_emision      date,
  clasif_cod         text,
  oc_numero          text,
  renglon            integer,
  remito_numero      text,
  proveedor_cod      text,
  cod_articulo       text,
  descripcion        text,
  cantidad_pedida    numeric,
  cantidad_recibida  numeric,
  cantidad_pendiente numeric,
  importe_neto       numeric,
  estado_oc          text,
  observacion        text,
  fecha_entrega      date,
  deposito           text,
  comprador          text,
  total_sin_iva_oc   numeric,
  total_con_iva_oc   numeric,
  condicion_compra   text,
  tipo_comprobante   text,
  comprobante_numero text,
  desc_comprobante   text,
  estado_pago        text
);

create table if not exists public.compras_ogs (
  id               bigint generated by default as identity primary key,
  numero           text default (nextval('public.compras_ogs_numero_seq')::text),
  fecha            date,
  proveedor_cod    text,
  proveedor        text,
  objeto           text,
  condicion        text,
  moneda           text,
  comprador        text,
  certificador     text,
  responsable      text,
  solp             integer,
  compra_urgente   text,
  costeo           text,
  estructura       text,
  postventa        text,
  desvio           text,
  desvio_txt       text,
  alcance          text,
  observaciones    text,
  monto_total      numeric default 0,
  items            jsonb default '[]'::jsonb,
  created_at       timestamptz default now(),
  anulada          boolean default false,
  anulada_por      text,
  anulada_fecha    timestamptz,
  clasif_og        text,
  tipo_contratacion text,
  anticipo_pct     numeric,
  anticipo_metodo  text,
  tc_pesos         numeric,
  creado_por       text,
  certificado_por  text,
  liberado_por     text,
  cerrada          boolean default false,
  cerrada_motivo   text,
  cerrada_texto    text,
  cerrada_por      text,
  cerrada_fecha    timestamptz,
  bonif_pct        numeric default 0,
  cierres          jsonb default '[]'::jsonb,
  pago_usd         boolean,
  lugar_pago       text,
  lugar_pago_txt   text
);

create table if not exists public.compras_og_certificados (
  id             bigint generated by default as identity primary key,
  og_id          bigint,
  numero         text,
  fecha          date,
  pct            numeric,
  avances        jsonb default '{}'::jsonb,
  aprobacion     text default 'NO',
  estado         text default 'Pendiente',
  pagado         boolean default false,
  fecha_pago     date,
  observaciones  text,
  created_at     timestamptz default now(),
  liberado_por   text,
  liberado_fecha date
);

create table if not exists public.compras_opciones_og (
  id    bigint generated by default as identity primary key,
  grupo text,
  valor text
);

create table if not exists public.compras_pagos (
  id             bigint generated by default as identity primary key,
  og_id          bigint,
  numero         text,
  fecha          date,
  pct            numeric,
  moneda_og      text,
  moneda_pago    text,
  tc             numeric,
  medio          text,
  caja_cod       text,
  importe_pago   numeric,
  observaciones  text,
  registrado_por text,
  created_at     timestamptz default now(),
  sin_caja       boolean,
  op_numero      bigint default nextval('public.compras_pagos_op_seq'),
  banco_transf   text,
  nro_asiento    text,
  registrado     boolean default false,
  asiento_num    text,
  ajuste_redondeo numeric,
  lugar_pago     text,
  lugar_pago_txt text
);

create table if not exists public.compras_panol_egresos (
  id             bigint generated by default as identity primary key,
  fecha          date not null,
  periodo        integer not null,
  cod_deposito   text not null,
  cod_articulo   text not null,
  cantidad       numeric not null,
  um             text,
  proyecto_cod   text not null,
  operario       text,
  costo_unit_ars numeric,
  costo_unit_usd numeric,
  total_ars      numeric,
  total_usd      numeric,
  exportado      boolean not null default false,
  exportado_en   timestamptz,
  comentario     text,
  creado_por     text
);

create table if not exists public.compras_proveedores (
  id           bigint generated by default as identity primary key,
  codigo       text,
  razon        text,
  comercial    text,
  cuit         text,
  tel          text,
  movil        text,
  email        text,
  web          text,
  provincia_cod text,
  provincia    text,
  actividad    text,
  iva          text,
  domicilio    text,
  cod_postal   text,
  tel2         text
);

create table if not exists public.compras_proyectos (
  id     bigint generated by default as identity primary key,
  codigo text,
  nombre text
);

create table if not exists public.compras_series (
  id          bigint generated by default as identity primary key,
  tipo        text,
  cod_art     text,
  descripcion text,
  serie       text
);

create table if not exists public.compras_series_activas (
  serie          text primary key,
  familia        text not null,
  cod_deposito   text,
  desc_deposito  text,
  cod_articulo   text,
  descripcion    text,
  comentario     text,
  adicional_1    text,
  adicional_2    text,
  codigo_barras  text,
  partida        text,
  numero_despacho text,
  actualizado_en timestamptz default now()
);
create index if not exists compras_series_activas_familia_idx
  on public.compras_series_activas (familia);

create table if not exists public.compras_solicitudes_pago (
  id             bigint generated by default as identity primary key,
  creado_en      timestamptz not null default now(),
  creado_por     text,
  proveedor_cod  text,
  proveedor      text,
  comprador      text,
  proyecto_cod   text,
  oc_numero      text,
  remito_numero  text,
  nro_factura    text,
  monto          numeric,
  moneda         text not null default 'ARS',
  adjunto_path   text,
  adjunto_nombre text,
  estado         text not null default 'Pendiente',
  historial      jsonb not null default '[]'::jsonb,
  actualizado_en timestamptz
);

-- stock_saldos NO tiene PK en aaqp (tabla plana que se resincroniza). Se replica igual.
create table if not exists public.compras_stock_saldos (
  cod_articulo     text not null,
  descripcion      text,
  cod_deposito     text not null,
  desc_deposito    text,
  um               text,
  saldo            numeric,
  cant_comprometida numeric,
  cant_a_recibir   numeric,
  punto_pedido     numeric,
  actualizado_en   timestamptz
);

create table if not exists public.compras_tipos_aux (
  id          bigint generated by default as identity primary key,
  codigo      text,
  descripcion text,
  restringido boolean default false
);

create table if not exists public.compras_ui_prefs (
  user_email text primary key,
  colwidths  jsonb not null default '{}'::jsonb
);

create table if not exists public.compras_usd_diario (
  fecha  date primary key,
  compra numeric not null,
  fuente text default 'manual',
  venta  numeric
);

create table if not exists public.compras_usd_diario_oficial (
  fecha  date primary key,
  compra numeric,
  venta  numeric,
  fuente text
);

create table if not exists public.compras_usuarios_autorizados (
  email           text primary key,
  nombre          text,
  es_tesorero     boolean default false,
  es_comprador    boolean default false,
  ve_confidencial boolean default false,
  es_certificador boolean default false,
  es_admin        boolean default false,
  es_finanzas     boolean default false
);

-- ===========================================================================
-- 2 · FOREIGN KEYS (se agregan al final para no depender del orden de creación)
-- ===========================================================================
do $$ begin
  alter table public.compras_herr_operaciones
    add constraint compras_herr_operaciones_herr_id_fkey
    foreign key (herr_id) references public.compras_herramientas (id);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.compras_inspecciones
    add constraint compras_inspecciones_item_id_fkey
    foreign key (item_id) references public.compras_mantenimiento (id);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.compras_og_certificados
    add constraint compras_og_certificados_og_id_fkey
    foreign key (og_id) references public.compras_ogs (id);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.compras_pagos
    add constraint compras_pagos_og_id_fkey
    foreign key (og_id) references public.compras_ogs (id);
exception when duplicate_object then null; end $$;

-- ===========================================================================
-- 3 · VISTA compras_usuarios_publicos (lista pública de nombres/roles).
--     Igual que en aaqp: SIN security_invoker → corre como owner y NO aplica
--     el RLS de compras_usuarios_autorizados (devuelve todos los nombres para
--     los desplegables). Solo expone nombre + flags de comprador/certificador.
-- ===========================================================================
create or replace view public.compras_usuarios_publicos as
  select nombre, es_comprador, es_certificador
    from public.compras_usuarios_autorizados;

-- ===========================================================================
-- 4 · Helper de flags internos de Compras (security definer → no depende del
--     RLS de compras_usuarios_autorizados). Devuelve el flag del usuario actual.
-- ===========================================================================
create or replace function public.compras_flag(p_flag text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select case p_flag
             when 'tesorero'     then u.es_tesorero
             when 'confidencial' then u.ve_confidencial
             when 'admin'        then u.es_admin
             when 'certificador' then u.es_certificador
             when 'comprador'    then u.es_comprador
             when 'finanzas'     then u.es_finanzas
             else false
           end
      from public.compras_usuarios_autorizados u
     where u.email = (auth.jwt() ->> 'email')
  ), false);
$$;
revoke all on function public.compras_flag(text) from public, anon;
grant execute on function public.compras_flag(text) to authenticated;

-- ===========================================================================
-- 5 · RLS + POLICIES + GRANTS
-- ===========================================================================
-- Convención: RLS on en todo; revoke anon; grant authenticated; policies con
-- compuerta de sector. tiene_sector() ya existe (000_portal_acceso.sql).

-- 5.a · Tablas "genéricas" de Compras: acceso total al sector compras.
do $$
declare t text;
begin
  foreach t in array array[
    'compras_articulos','compras_certificadores','compras_clasif_comprobantes',
    'compras_depositos','compras_herr_operaciones','compras_herramientas',
    'compras_inspecciones','compras_mantenimiento','compras_modulos',
    'compras_motivos_cierre','compras_oc_informe','compras_og_certificados',
    'compras_ogs','compras_opciones_og','compras_panol_egresos',
    'compras_proveedores','compras_proyectos','compras_series',
    'compras_series_activas','compras_solicitudes_pago','compras_stock_saldos',
    'compras_idx_cac','compras_idx_dolar_blue','compras_idx_dolar_oficial',
    'compras_idx_ipc','compras_idx_poli','compras_idx_uva'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('drop policy if exists compras_sector on public.%I', t);
    execute format($f$create policy compras_sector on public.%I
                     for all to authenticated
                     using (public.tiene_sector('compras'::public.sector_portal))
                     with check (public.tiene_sector('compras'::public.sector_portal))$f$, t);
  end loop;
end $$;

-- 5.b · Tablas de referencia que EERR también LEE (compras+eerr select; compras write).
do $$
declare t text;
begin
  foreach t in array array[
    'compras_usd_diario','compras_usd_diario_oficial',
    'compras_idx_facpce','compras_clasif_renglon'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('drop policy if exists compras_ref_sel on public.%I', t);
    execute format('drop policy if exists compras_ref_write on public.%I', t);
    execute format($f$create policy compras_ref_sel on public.%I
                     for select to authenticated
                     using (public.tiene_sector('compras'::public.sector_portal)
                         or public.tiene_sector('eerr'::public.sector_portal))$f$, t);
    execute format($f$create policy compras_ref_write on public.%I
                     for all to authenticated
                     using (public.tiene_sector('compras'::public.sector_portal))
                     with check (public.tiene_sector('compras'::public.sector_portal))$f$, t);
  end loop;
end $$;

-- 5.c · clasif_proyecto_eerr: dominio EERR; compras+eerr leen y escriben.
alter table public.compras_clasif_proyecto_eerr enable row level security;
revoke all on public.compras_clasif_proyecto_eerr from anon;
grant select, insert, update, delete on public.compras_clasif_proyecto_eerr to authenticated;
drop policy if exists compras_eerr_all on public.compras_clasif_proyecto_eerr;
create policy compras_eerr_all on public.compras_clasif_proyecto_eerr
  for all to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) or public.tiene_sector('eerr'::public.sector_portal))
  with check (public.tiene_sector('compras'::public.sector_portal) or public.tiene_sector('eerr'::public.sector_portal));

-- 5.d · eerr_estado: dominio EERR puro.
alter table public.eerr_estado enable row level security;
revoke all on public.eerr_estado from anon;
grant select, insert, update, delete on public.eerr_estado to authenticated;
drop policy if exists eerr_sector on public.eerr_estado;
create policy eerr_sector on public.eerr_estado
  for all to authenticated
  using (public.tiene_sector('eerr'::public.sector_portal))
  with check (public.tiene_sector('eerr'::public.sector_portal));

-- 5.e · Confidenciales por columna (SELECT filtra confidencial; escritura admin).
--       aux_opciones y cuentas_contables: ver no-confidenciales o si ve_confidencial;
--       alta/edición solo es_admin. aux_tipos: ver/editar según confidencial.
alter table public.compras_aux_opciones enable row level security;
revoke all on public.compras_aux_opciones from anon;
grant select, insert, update, delete on public.compras_aux_opciones to authenticated;
drop policy if exists compras_auxo_sel on public.compras_aux_opciones;
drop policy if exists compras_auxo_ins on public.compras_aux_opciones;
drop policy if exists compras_auxo_upd on public.compras_aux_opciones;
create policy compras_auxo_sel on public.compras_aux_opciones
  for select to authenticated
  using (public.tiene_sector('compras'::public.sector_portal)
         and (confidencial = false or public.compras_flag('confidencial')));
create policy compras_auxo_ins on public.compras_aux_opciones
  for insert to authenticated
  with check (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('admin'));
create policy compras_auxo_upd on public.compras_aux_opciones
  for update to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('admin'));

alter table public.compras_cuentas_contables enable row level security;
revoke all on public.compras_cuentas_contables from anon;
grant select, insert, update, delete on public.compras_cuentas_contables to authenticated;
drop policy if exists compras_conta_sel on public.compras_cuentas_contables;
drop policy if exists compras_conta_ins on public.compras_cuentas_contables;
drop policy if exists compras_conta_upd on public.compras_cuentas_contables;
create policy compras_conta_sel on public.compras_cuentas_contables
  for select to authenticated
  using (public.tiene_sector('compras'::public.sector_portal)
         and (confidencial = false or public.compras_flag('confidencial')));
create policy compras_conta_ins on public.compras_cuentas_contables
  for insert to authenticated
  with check (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('admin'));
create policy compras_conta_upd on public.compras_cuentas_contables
  for update to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('admin'));

alter table public.compras_aux_tipos enable row level security;
revoke all on public.compras_aux_tipos from anon;
grant select, insert, update, delete on public.compras_aux_tipos to authenticated;
drop policy if exists compras_auxt_sel on public.compras_aux_tipos;
drop policy if exists compras_auxt_upd on public.compras_aux_tipos;
create policy compras_auxt_sel on public.compras_aux_tipos
  for select to authenticated
  using (public.tiene_sector('compras'::public.sector_portal)
         and (confidencial = false or public.compras_flag('confidencial')));
create policy compras_auxt_upd on public.compras_aux_tipos
  for update to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('confidencial'));

-- 5.f · Confidenciales por tabla completa: cuentas y tipos_aux (solo ve_confidencial).
do $$
declare t text;
begin
  foreach t in array array['compras_cuentas','compras_tipos_aux']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('drop policy if exists compras_conf_all on public.%I', t);
    execute format($f$create policy compras_conf_all on public.%I
                     for all to authenticated
                     using (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('confidencial'))
                     with check (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('confidencial'))$f$, t);
  end loop;
end $$;

-- 5.g · idx_sueldos: confidencial (ve_confidencial o admin).
alter table public.compras_idx_sueldos enable row level security;
revoke all on public.compras_idx_sueldos from anon;
grant select, insert, update, delete on public.compras_idx_sueldos to authenticated;
drop policy if exists compras_sueldos_all on public.compras_idx_sueldos;
create policy compras_sueldos_all on public.compras_idx_sueldos
  for all to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) and (public.compras_flag('confidencial') or public.compras_flag('admin')))
  with check (public.tiene_sector('compras'::public.sector_portal) and (public.compras_flag('confidencial') or public.compras_flag('admin')));

-- 5.h · Tesorería: caja y pagos (todos en sector ven; solo tesorero escribe).
do $$
declare t text;
begin
  foreach t in array array['compras_caja','compras_pagos']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('drop policy if exists compras_teso_sel on public.%I', t);
    execute format('drop policy if exists compras_teso_all on public.%I', t);
    execute format($f$create policy compras_teso_sel on public.%I
                     for select to authenticated
                     using (public.tiene_sector('compras'::public.sector_portal))$f$, t);
    execute format($f$create policy compras_teso_all on public.%I
                     for all to authenticated
                     using (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('tesorero'))
                     with check (public.tiene_sector('compras'::public.sector_portal) and public.compras_flag('tesorero'))$f$, t);
  end loop;
end $$;

-- 5.i · caja_ingresos: en aaqp tenía RLS apagado (agujero). Acá: sector compras.
alter table public.compras_caja_ingresos enable row level security;
revoke all on public.compras_caja_ingresos from anon;
grant select, insert, update, delete on public.compras_caja_ingresos to authenticated;
drop policy if exists compras_sector on public.compras_caja_ingresos;
create policy compras_sector on public.compras_caja_ingresos
  for all to authenticated
  using (public.tiene_sector('compras'::public.sector_portal))
  with check (public.tiene_sector('compras'::public.sector_portal));

-- 5.j · ui_prefs: cada usuario solo su propia fila (dentro del sector).
alter table public.compras_ui_prefs enable row level security;
revoke all on public.compras_ui_prefs from anon;
grant select, insert, update, delete on public.compras_ui_prefs to authenticated;
drop policy if exists compras_uiprefs_own on public.compras_ui_prefs;
create policy compras_uiprefs_own on public.compras_ui_prefs
  for all to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) and user_email = (auth.jwt() ->> 'email'))
  with check (public.tiene_sector('compras'::public.sector_portal) and user_email = (auth.jwt() ->> 'email'));

-- 5.k · usuarios_autorizados: cada uno lee su propia fila (para resolver sus flags).
alter table public.compras_usuarios_autorizados enable row level security;
revoke all on public.compras_usuarios_autorizados from anon;
grant select, insert, update, delete on public.compras_usuarios_autorizados to authenticated;
drop policy if exists compras_ua_self on public.compras_usuarios_autorizados;
create policy compras_ua_self on public.compras_usuarios_autorizados
  for select to authenticated
  using (public.tiene_sector('compras'::public.sector_portal) and email = (auth.jwt() ->> 'email'));

-- 5.l · Vista pública: legible por el sector compras (corre como owner, ver arriba).
revoke all on public.compras_usuarios_publicos from anon;
grant select on public.compras_usuarios_publicos to authenticated;

-- 5.m · Secuencias: usage para authenticated (identity + las 2 explícitas).
grant usage, select on sequence public.compras_ogs_numero_seq to authenticated;
grant usage, select on sequence public.compras_pagos_op_seq to authenticated;
-- (las secuencias de identity heredan el grant por default de Supabase; si algún
--  insert fallara por permiso de secuencia, correr:
--    grant usage on all sequences in schema public to authenticated; )

-- ===========================================================================
-- FIN. Datos en 115_datos_compras.sql (local, gitignoreado). Después de cargar
-- datos, ese archivo hace setval de las secuencias/identity a su valor actual.
-- ===========================================================================
